### ISSUE TITLE
Errors while running

### ISSUE THREAD

**Issue by resiproxy** [preram48/sonarr-trakt-tv#7]
So this worked for about three minutes but now I am getting alot of errors thrown. Didn't end up important everything in my trakt lists. Any ideas?

> sonarr-trakt-tv@0.0.0 dev /opt/sonarr-trakt-tv
> concurrently "npm run tsc-watch" "npm run nodemon"

[1]
[1] > sonarr-trakt-tv@0.0.0 nodemon /opt/sonarr-trakt-tv
[1] > nodemon -r dotenv/config --delay 1500ms --watch dev.env --watch ./build "./build/app.js" dotenv_config_path=dev.env
[1]
[0]
[0] > sonarr-trakt-tv@0.0.0 tsc-watch /opt/sonarr-trakt-tv
[0] > tsc -w
[0]
[0] 2:26:23 PM - Starting compilation in watch mode...
[0]
[1] [nodemon] 1.18.4
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: dev.env /opt/sonarr-trakt-tv/build/**/*
[1] [nodemon] starting `node -r dotenv/config ./build/app.js dotenv_config_path=dev.env`
[1] events.js:167
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::9500
[1]     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
[1]     at listenInCluster (net.js:1334:12)
[1]     at Server.listen (net.js:1421:7)
[1]     at Function.listen (/opt/sonarr-trakt-tv/node_modules/inversify-express-utils/node_modules/express/lib/application.js:618:24)
[1]     at Object.<anonymous> (/opt/sonarr-trakt-tv/build/app.js:35:5)
[1]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[1]     at Module.load (internal/modules/cjs/loader.js:598:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[1] Emitted 'error' event at:
[1]     at emitErrorNT (net.js:1313:8)
[1]     at process._tickCallback (internal/process/next_tick.js:63:19)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
[1]     at startup (internal/bootstrap/node.js:285:19)
[1]     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[1] [nodemon] app crashed - waiting for file changes before starting...
[0]
[0] 2:26:25 PM - Found 0 errors. Watching for file changes.
[1] [nodemon] restarting due to changes...
[1] [nodemon] starting `node -r dotenv/config ./build/app.js dotenv_config_path=dev.env`
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:20827) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[1] (node:20827) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:20827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)

**Comment by preram48** [comment]
Looks like port 9500 is already in use. You can change the port number in src/api/app.ts. If you are also using docker you will have to edit the docker files exposed port.

**Comment by resiproxy** [comment]
Changed the port but still the same issue. It's weird because it says it can't bind to the port but then it does. I can go to the site and set up the connection to sonarr and trakt. It's sent some Tv shows to download fine. But now it has stopped

Property 'title' undefined error?

[1] > sonarr-trakt-tv@0.0.0 nodemon /opt/sonarr-trakt-tv
[1] > nodemon -r dotenv/config --delay 1500ms --watch dev.env --watch ./build "./build/app.js" dotenv_config_path=dev.env
[1]
[0] 5:51:38 PM - Starting compilation in watch mode...
[0]
[1] [nodemon] 1.18.4
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: dev.env /opt/sonarr-trakt-tv/build/**/*
[1] [nodemon] starting `node -r dotenv/config ./build/app.js dotenv_config_path=dev.env`
[1] events.js:167
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::19512
[1]     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
[1]     at listenInCluster (net.js:1334:12)
[1]     at Server.listen (net.js:1421:7)
[1]     at Function.listen (/opt/sonarr-trakt-tv/node_modules/inversify-express-utils/node_modules/express/lib/application.js:618:24)
[1]     at Object.<anonymous> (/opt/sonarr-trakt-tv/build/app.js:35:5)
[1]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[1]     at Module.load (internal/modules/cjs/loader.js:598:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[1] Emitted 'error' event at:
[1]     at emitErrorNT (net.js:1313:8)
[1]     at process._tickCallback (internal/process/next_tick.js:63:19)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
[1]     at startup (internal/bootstrap/node.js:285:19)
[1]     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[1] [nodemon] app crashed - waiting for file changes before starting...
[0]
[0] 5:51:40 PM - Found 0 errors. Watching for file changes.
[1] [nodemon] restarting due to changes...
[1] [nodemon] starting `node -r dotenv/config ./build/app.js dotenv_config_path=dev.env`
[1] (node:4637) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
[1]     at SonarrService.<anonymous> (/opt/sonarr-trakt-tv/build/services/SonarrService.js:125:66)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/opt/sonarr-trakt-tv/build/services/SonarrService.js:13:58)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:4637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:4637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
